server:
  port: 8055
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: xxx
    password: xxx
    url: jdbc:mysql://2c:59999/spider?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true
  elasticsearch:
    rest:
      username:
      uris: http://2ch:59393
      password:
      read-timeout: 5000
spider:
  nns:
    connectURL: guangchang.tech:59393